# Generated by Django 2.2 on 2018-07-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180718_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meme',
        ),
    ]
