# Generated by Django 2.2 on 2018-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meme',
            field=models.ImageField(default=1, upload_to='memes/'),
            preserve_default=False,
        ),
    ]
