# Generated by Django 2.2 on 2018-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meme',
            field=models.FileField(upload_to='meme/'),
        ),
    ]
