# Generated by Django 2.2 on 2018-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180719_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meme',
            field=models.FileField(upload_to=''),
        ),
    ]
